/-
Copyright (c) 2026.
SPDX-License-Identifier: Apache-2.0
-/
import Zeta23.ZeroSide
import ZetaSeven.Stability

/-!
# The simple-zero Gram block inside the multiplicity-aware zero side

This file performs the finite-dimensional decomposition needed by the
seven-point refinement.  The upstream multiplicity-aware proof puts every
on-line zero, with its multiplicity, into the positive block.  Here we put
only simple on-line zeros into `simpleP`; multiple on-line zeros move into
the remainder.  The remainder has positive index at most `s₂ + p`.

The final theorem is the exact finite zero-side inequality in the manuscript,
with the spectral defect of the simple-zero Gram matrix retained.
-/

noncomputable section
set_option linter.unusedSectionVars false

open Matrix Finset RHLinalg
open scoped ComplexOrder BigOperators
open Zeta23.ZeroSide
open Zeta23.ZeroSide.RankTraceMult
open ZetaSeven.Stability

namespace Zeta23.ZeroSide.ZeroBlockData

variable {ι d : Type*} [Fintype ι] [DecidableEq ι]
  [Fintype d] [DecidableEq d]

variable (D : Zeta23.ZeroSide.ZeroBlockData ι d)

/-- The unnormalized contribution of the simple on-line zeros. -/
def simpleOnPart : Matrix d d ℂ :=
  ∑ z ∈ D.S₁, (D.m z : ℂ) • Matrix.vecMulVec (D.v z) (D.v z)

/-- The unnormalized contribution of the multiple on-line zeros. -/
def multipleOnPart : Matrix d d ℂ :=
  ∑ z ∈ D.S₂, (D.m z : ℂ) • Matrix.vecMulVec (D.v z) (D.v z)

lemma onPart_eq_simple_add_multiple :
    D.onPart = D.simpleOnPart + D.multipleOnPart := by
  unfold Zeta23.ZeroSide.ZeroBlockData.onPart simpleOnPart multipleOnPart
  rw [D.onLine_eq_S₁_union_S₂,
    Finset.sum_union D.disjoint_S₁_S₂]

lemma simpleOnPart_posSemidef : D.simpleOnPart.PosSemidef := by
  unfold simpleOnPart
  refine posSemidef_sum _ fun z hz => ?_
  have hon : z ∈ D.onLine := by
    simp only [Zeta23.ZeroSide.ZeroBlockData.S₁, Finset.mem_filter,
      Finset.mem_univ, true_and] at hz
    exact D.mem_onLine.mpr hz.1
  exact Zeta23.ZeroSide.ZeroBlockData.posSemidef_smul_vecMulVec
    (D.star_v_of_onLine (D.mem_onLine.mp hon)) (Nat.cast_nonneg (D.m z))

lemma multipleOnPart_posSemidef : D.multipleOnPart.PosSemidef := by
  unfold multipleOnPart
  refine posSemidef_sum _ fun z hz => ?_
  have hon : z ∈ D.onLine := by
    simp only [Zeta23.ZeroSide.ZeroBlockData.S₂, Finset.mem_filter,
      Finset.mem_univ, true_and] at hz
    exact D.mem_onLine.mpr hz.1
  exact Zeta23.ZeroSide.ZeroBlockData.posSemidef_smul_vecMulVec
    (D.star_v_of_onLine (D.mem_onLine.mp hon)) (Nat.cast_nonneg (D.m z))

lemma rank_multipleOnPart_le : D.multipleOnPart.rank ≤ D.s₂ := by
  unfold multipleOnPart Zeta23.ZeroSide.ZeroBlockData.s₂
  refine (rank_sum_le _ _ (fun _ => 1)
    fun z _ => rank_smul_vecMulVec_le _ _ _).trans ?_
  simp

/-- The normalized columns indexed only by simple on-line zeros. -/
def simpleVhat (c : ℝ) : D.S₁ → d → ℂ :=
  fun z k => D.v z k / (Real.sqrt c : ℂ)

/-- The column matrix of normalized simple-zero atoms. -/
def simpleW (c : ℝ) : Matrix d D.S₁ ℂ :=
  Wmat (fun _ : D.S₁ => (1 : ℝ)) (D.simpleVhat c)

/-- The PSD matrix generated by the normalized simple-zero columns. -/
def simpleP (c : ℝ) : Matrix d d ℂ :=
  Pmat (fun _ : D.S₁ => (1 : ℝ)) (D.simpleVhat c)

lemma simpleP_eq_simpleW_mul (c : ℝ) :
    D.simpleP c = D.simpleW c * (D.simpleW c)ᴴ := by
  rfl

/-- `simpleP` is the normalized sum over exactly `S₁`. -/
lemma simpleP_eq_scaled_simpleOnPart {c : ℝ} (hc : 0 < c) :
    D.simpleP c = ((c⁻¹ : ℝ) : ℂ) • D.simpleOnPart := by
  ext a b
  unfold simpleP
  rw [Pmat_apply (fun _ : D.S₁ => by norm_num)]
  simp only [simpleVhat, simpleOnPart, Matrix.smul_apply,
    Matrix.sum_apply, smul_eq_mul, Finset.mul_sum]
  rw [← Finset.sum_coe_sort D.S₁]
  refine Finset.sum_congr rfl fun z _ => ?_
  have hz : D.σ z = z := by
    have := z.2
    simp only [Zeta23.ZeroSide.ZeroBlockData.S₁, Finset.mem_filter,
      Finset.mem_univ, true_and] at this
    exact this.1
  have hreal : starRingEnd ℂ (D.v z b) = D.v z b := by
    have h := congrFun (D.star_v_of_onLine hz) b
    rwa [Pi.star_apply, RCLike.star_def] at h
  rw [map_div₀, hreal, Complex.conj_ofReal]
  have hsq : ((Real.sqrt c : ℂ)) ^ 2 = (c : ℂ) := by
    rw [sq, ← Complex.ofReal_mul, Real.mul_self_sqrt hc.le]
  have hc0 : (Real.sqrt c : ℂ) ≠ 0 := by
    exact_mod_cast (Real.sqrt_pos.mpr hc).ne'
  have hcc : (c : ℂ) ≠ 0 := by exact_mod_cast hc.ne'
  have hm : D.m z = 1 := by
    have := z.2
    simp only [Zeta23.ZeroSide.ZeroBlockData.S₁, Finset.mem_filter,
      Finset.mem_univ, true_and] at this
    exact this.2
  rw [hm]
  norm_num
  rw [div_mul_div_comm, ← sq, hsq]
  field_simp
  rfl

lemma simpleP_posSemidef (c : ℝ) : (D.simpleP c).PosSemidef :=
  Pmat_posSemidef _ _

/-- The normalized contribution of the multiple on-line zeros. -/
def multipleP (c : ℝ) : Matrix d d ℂ :=
  ((c⁻¹ : ℝ) : ℂ) • D.multipleOnPart

lemma multipleP_posSemidef {c : ℝ} (hc : 0 < c) :
    (D.multipleP c).PosSemidef :=
  D.multipleOnPart_posSemidef.smul
    (Complex.zero_le_real.mpr (inv_nonneg.mpr hc.le))

lemma rank_multipleP_le {c : ℝ} (hc : 0 < c) :
    (D.multipleP c).rank ≤ D.s₂ := by
  unfold multipleP
  rw [rank_smul_of_ne_zero _ (by exact_mod_cast (inv_ne_zero hc.ne'))]
  exact D.rank_multipleOnPart_le

lemma blockP_eq_simpleP_add_multipleP {c : ℝ} (hc : 0 < c) :
    D.blockP c = D.simpleP c + D.multipleP c := by
  rw [D.simpleP_eq_scaled_simpleOnPart hc]
  unfold Zeta23.ZeroSide.ZeroBlockData.blockP multipleP
  rw [D.onPart_eq_simple_add_multiple, smul_add]

/-- The full normalized zero matrix. -/
def simpleAhat (c : ℝ) : Matrix d d ℂ :=
  ((c⁻¹ : ℝ) : ℂ) • D.blockA

/-- Everything except the normalized simple-zero PSD block. -/
def simpleQ (c : ℝ) : Matrix d d ℂ := D.simpleAhat c - D.simpleP c

lemma simpleAhat_eq_simpleP_add_simpleQ (c : ℝ) :
    D.simpleP c + D.simpleQ c = D.simpleAhat c := by
  unfold simpleQ
  abel

lemma simpleQ_eq_multipleP_add_blockQ {c : ℝ} (hc : 0 < c) :
    D.simpleQ c = D.multipleP c + D.blockQ c := by
  unfold simpleQ simpleAhat
  rw [← D.blockP_add_blockQ c, D.blockP_eq_simpleP_add_multipleP hc]
  abel

lemma simpleQ_isHermitian (c : ℝ) : (D.simpleQ c).IsHermitian := by
  unfold simpleQ simpleAhat
  exact (Zeta23.ZeroSide.ZeroBlockData.isHermitian_real_smul
    D.blockA_isHermitian _).sub (D.simpleP_posSemidef c).isHermitian

/-- Moving multiple on-line zeros into the remainder costs at most `s₂`
additional positive directions. -/
theorem posIndex_simpleQ_le (Pr : D.PairReps) {c : ℝ} (hc : 0 < c) :
    posIndex (D.simpleQ_isHermitian c) ≤ D.s₂ + Pr.p := by
  have hM := D.multipleP_posSemidef hc
  have hQ := D.blockQ_isHermitian c
  have hsum := posIndex_add_le hM.isHermitian hQ
  rw [posIndex_eq_rank_of_posSemidef hM] at hsum
  have hbound := Nat.add_le_add (D.rank_multipleP_le hc)
    (D.posIndex_blockQ_le Pr hc)
  rw [Zeta23.ZeroSide.ZeroBlockData.posIndex_congr
    (D.simpleQ_isHermitian c) (hM.isHermitian.add hQ)
    (D.simpleQ_eq_multipleP_add_blockQ hc)]
  exact hsum.trans hbound

lemma xsq_simpleVhat_le {c : ℝ} (hc : 0 < c)
    (hPois : ∀ z ∈ D.onLine, ∑ k, ‖D.v z k‖ ^ 2 ≤ c)
    (z : D.S₁) : xsq (D.simpleVhat c) z ≤ 1 := by
  unfold xsq simpleVhat
  have hon : (z : ι) ∈ D.onLine := by
    have hz := z.2
    simp only [Zeta23.ZeroSide.ZeroBlockData.S₁, Finset.mem_filter,
      Finset.mem_univ, true_and] at hz
    exact D.mem_onLine.mpr hz.1
  have hs : ∀ k, ‖D.v z k / (Real.sqrt c : ℂ)‖ ^ 2
      = ‖D.v z k‖ ^ 2 / c := by
    intro k
    rw [norm_div, Complex.norm_real, Real.norm_eq_abs,
      abs_of_pos (Real.sqrt_pos.mpr hc), div_pow, Real.sq_sqrt hc.le]
  simp_rw [hs]
  rw [← Finset.sum_div, div_le_one hc]
  exact hPois z hon

lemma rtrace_simpleP_le_card {c : ℝ} (hc : 0 < c)
    (hPois : ∀ z ∈ D.onLine, ∑ k, ‖D.v z k‖ ^ 2 ≤ c) :
    rtrace (D.simpleP c) ≤ (Fintype.card D.S₁ : ℝ) := by
  unfold simpleP
  rw [rtrace_Pmat (fun _ : D.S₁ => by norm_num)]
  simp only [one_mul]
  calc
    (∑ z : D.S₁, xsq (D.simpleVhat c) z)
        ≤ ∑ _z : D.S₁, (1 : ℝ) :=
          Finset.sum_le_sum fun z _ => D.xsq_simpleVhat_le hc hPois z
    _ = (Fintype.card D.S₁ : ℝ) := by simp

/-- Finite-dimensional stability inequality with the spectral defect of the
simple-zero Gram matrix retained. -/
theorem simple_gram_defect_rank_trace (Pr : D.PairReps) {c : ℝ} (hc : 0 < c)
    (hPois : ∀ z ∈ D.onLine, ∑ k, ‖D.v z k‖ ^ 2 ≤ c) :
    4 * rtrace (D.simpleAhat c) - 3 * (D.s₁ : ℝ)
        - 4 * ((D.s₂ + Pr.p : ℕ) : ℝ)
        + spectralDefect
          (Matrix.posSemidef_conjTranspose_mul_self (D.simpleW c))
      ≤ frobSq (D.simpleAhat c) := by
  have h := gram_defect_rank_trace (D.simpleW c)
    (D.simpleQ_isHermitian c) (D.posIndex_simpleQ_le Pr hc)
    (D.rtrace_simpleP_le_card hc hPois)
  rw [← D.simpleP_eq_simpleW_mul c, D.simpleAhat_eq_simpleP_add_simpleQ c] at h
  simpa [Zeta23.ZeroSide.ZeroBlockData.s₁] using h

/-- The exact finite simple-zero count inequality before analytic trace and
tail estimates are substituted. -/
theorem finite_simple_zero_counting (Pr : D.PairReps) {c : ℝ} (hc : 0 < c)
    (hPois : ∀ z ∈ D.onLine, ∑ k, ‖D.v z k‖ ^ 2 ≤ c) :
    4 * rtrace (D.simpleAhat c) - frobSq (D.simpleAhat c)
        - 2 * (D.Ncount : ℝ)
        + spectralDefect
          (Matrix.posSemidef_conjTranspose_mul_self (D.simpleW c))
      ≤ (D.s₁ : ℝ) := by
  have hstable := D.simple_gram_defect_rank_trace Pr hc hPois
  have hcount : (D.s₁ : ℝ) + 2 * D.s₂ + 2 * Pr.p ≤ D.Ncount := by
    exact_mod_cast D.s₁_add_two_s₂_add_two_p_le_Ncount Pr
  push_cast at hstable hcount ⊢
  linarith

end Zeta23.ZeroSide.ZeroBlockData

namespace ZetaSeven.SimpleBlock

open Zeta23 Classical
open Zeta23.ZeroSide

variable (Z : ZeroConfig) (T : ℝ) (P : Params)

/-- Concrete simple-zero column matrix for the zero configuration in `I'`. -/
def zetaSimpleW (hconj : PhiHatConj T P) :
    Matrix (Fin (P.d T)) (blockData Z T P hconj).S₁ ℂ :=
  (blockData Z T P hconj).simpleW (P.a T * P.L T ^ 2)

/-- The paper's exact finite zero-side inequality, now instantiated against
the actual zeta-zero data and retaining the simple-zero Gram defect. -/
theorem hatAz_simple_defect
    (hconj : PhiHatConj T P) (hreal : PhiHatReal T P)
    (hPois : PoissonSq T P) (hc : 0 < P.a T * P.L T ^ 2) :
    4 * rtrace (P.hat T (Z.Az P T))
        - frobSq (P.hat T (Z.Az P T))
        - 2 * (Z.NIprime T : ℝ)
        + spectralDefect
          (Matrix.posSemidef_conjTranspose_mul_self
            (zetaSimpleW Z T P hconj))
      ≤ (Z.s1 T : ℝ) := by
  let D := blockData Z T P hconj
  have h := D.finite_simple_zero_counting
    (mkPairReps Z T _ (evalVec_reflect hconj)) hc
    (sum_normSq_v_le Z T P hconj hreal hPois)
  have hA : P.hat T (Z.Az P T) = D.simpleAhat (P.a T * P.L T ^ 2) := by
    simp only [D, Zeta23.ZeroSide.ZeroBlockData.simpleAhat]
    rw [hat_eq, Az_eq_blockA Z T P hconj]
  rw [hA, NIprime_eq_mk Z T _ (evalVec_reflect hconj),
    s1_eq_mk Z T _ (evalVec_reflect hconj)]
  simpa [D, zetaSimpleW, blockData] using h

end ZetaSeven.SimpleBlock
